version: '3'

services:
  jenkins_node:
    image: luised160/s107-jenkins-node:TAG
    container_name: jenkins
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
     - 3333:3333
    # volumes:
    #   - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
    #   - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - rs-network
      
  database:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    command: ["mysqld", "--mysql-native-password=ON"]
    ports:
      - '3307:3306'
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=database
    networks:
      - rs-network

  redis:
    image: bitnami/redis
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=12345
      - REDIS_PREFIX=api
    networks:
      - rs-network
    

networks:
  rs-network:
    driver: bridge

 